'use strict';
const $=id=>document.getElementById(id);
let state=null,projectId=null,workspaceId=null,loading=false,connectionError=false;
const statuses={queued:'대기',running:'실행 중',stopping:'취소 중',succeeded:'성공',failed:'실패',cancelled:'취소',interrupted:'중단 후 정리됨',recovery_required:'복구 확인 필요'};
const names={orca:'Orca',codex:'Codex',claude:'Claude',gemini:'Gemini CLI',antigravity:'Antigravity',folder:'폴더 열기',terminal:'개발 터미널'};
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);$('message').setAttribute('role',error?'alert':'status');}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function button(text,fn){const el=node('button',text);el.type='button';el.addEventListener('click',()=>action(fn,el));return el;}
async function api(path,data,key){const headers={};if(data!==undefined)headers['Content-Type']='application/json';if(key)headers['Idempotency-Key']=key;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),70000);try{const response=await fetch(path,{method:data===undefined?'GET':'POST',headers,body:data===undefined?undefined:JSON.stringify(data),signal:controller.signal,cache:'no-store'});const value=await response.json();if(response.status===401){$('login').hidden=false;$('app').hidden=true;}if(!response.ok)throw new Error(value.error||'요청을 처리하지 못했습니다.');return value;}finally{clearTimeout(timer);}}
async function action(fn,el){if(el)el.disabled=true;try{await fn();await refresh();}catch(e){message(e.message,true);}finally{if(el)el.disabled=false;}}
function current(){return state?.projects.find(p=>p.id===projectId);}
function renderProject(){const p=current();$('projectTitle').textContent=p?.name||'프로젝트를 생성하세요';$('projectKind').textContent=p?.kind==='ai'?'AI · CPU 학습':p?.kind==='python'?'일반 개발':'기존 프로젝트';$('projectPath').textContent=p?.path||'';const select=$('workspace');select.replaceChildren();if(p){if(!p.workspaces.some(w=>w.id===workspaceId))workspaceId=p.workspaces.find(w=>w.role==='main')?.id;for(const w of p.workspaces){const option=node('option',w.role+' · '+w.path);option.value=w.id;select.append(option);}select.value=workspaceId;}const tools=$('tools');tools.replaceChildren();for(const tool of Object.keys(names)){const b=button(names[tool],async()=>{await api('/api/open',{project:projectId,workspace:workspaceId,tool});message(names[tool]+' 실행 요청을 보냈습니다. 열린 창에서 개발을 시작하세요.');});b.disabled=!p||(!(tool in {folder:1,terminal:1})&&!state.tools[tool]);tools.append(b);}const tasks=$('tasks');tasks.replaceChildren();for(const [task,config] of Object.entries(p?.tasks||{})){const b=button(config.label,async()=>{const result=await api('/api/jobs',{project:projectId,workspace:workspaceId,task},crypto.randomUUID());message('작업을 제출했습니다: '+result.id);});b.classList.add('primary');b.disabled=!state.imageConfigured||state.jobs.some(j=>['queued','running','stopping','recovery_required'].includes(j.status));tasks.append(b);}if(!Object.keys(p?.tasks||{}).length)tasks.append(node('p','이 프로젝트는 도구에서 개발·빌드합니다. 웹 실행 작업은 아직 등록하지 않았습니다.','muted'));$('newWorkspace').disabled=!p;}
function renderJobs(){const pane=$('jobs');const open=new Set([...pane.querySelectorAll('details[open]')].map(x=>x.dataset.id));pane.replaceChildren();const jobs=state.jobs.filter(j=>j.project===projectId);if(!jobs.length)pane.append(node('p','아직 실행한 개발 작업이 없습니다. 위에서 첫 작업을 실행하세요.'));for(const job of jobs){const details=node('details');details.dataset.id=job.id;details.open=open.has(job.id);const summary=node('summary');summary.append(node('span',job.task+' · '+new Date(job.created*1000).toLocaleString('ko-KR')),node('strong',statuses[job.status]||job.status,job.status==='succeeded'?'good':['failed','recovery_required'].includes(job.status)?'bad':''));details.append(summary,node('p',job.id,'path'));const r=job.record;details.append(node('p','실행 위치: '+r.machine+' · 종료 코드: '+(r.exitCode??'미확인')+' · '+(r.reason||'')));if(r.error)details.append(node('p',r.error,'bad'));if(r.recovery)details.append(node('p',r.recovery));details.append(node('p','입력 SHA-256: '+r.inputSha256,'path'));if(r.enforced)details.append(node('p','실제 적용: CPU '+r.enforced.cpuMillis/1000+' · RAM '+r.enforced.memoryBytes/1024**2+' MiB · network '+r.enforced.network+' · 종료 확인 '+(r.stopped?'완료':'진행 중'),'muted'));if(['queued','running','stopping','recovery_required'].includes(job.status))details.append(button('작업 취소',async()=>{await api('/api/cancel',{id:job.id});message('취소 요청을 처리했습니다.');}));for(const stream of ['stdout','stderr'])if(r[stream])details.append(node('h3',stream==='stdout'?'실제 표준 출력':'실제 오류 출력'),node('pre',r[stream]),node('p','SHA-256: '+r[stream+'Sha256'],'path'));for(const a of r.artifacts||[]){const link=node('a',a.path+' 내려받기 ('+a.sizeBytes+' bytes)');link.href='/api/artifact?job='+encodeURIComponent(job.id)+'&path='+encodeURIComponent(a.path);link.download=a.path.split('/').pop();details.append(link,node('p',a.sha256,'path'));}pane.append(details);}}
function render(){const pane=$('projects');pane.replaceChildren();if(!state.projects.some(p=>p.id===projectId))projectId=state.projects[0]?.id;for(const p of state.projects){const b=button(p.name,async()=>{projectId=p.id;workspaceId=null;render();});b.setAttribute('aria-current',String(p.id===projectId));pane.append(b);}if(!state.projects.length)pane.append(node('p','등록된 프로젝트가 없습니다.'));$('cpu').textContent=state.budget.cpuMillis/1000;$('memory').textContent=state.budget.memoryMiB;$('timeout').textContent=state.budget.timeoutSeconds;if(!loading){for(const [key,value] of Object.entries(state.budget))$('budget').elements[key].value=value;}renderProject();renderJobs();}
async function refresh(){try{state=await api('/api/status');$('login').hidden=true;$('app').hidden=false;if(connectionError){message('개발 Studio 연결이 복구되었습니다.');connectionError=false;}render();}catch(e){state=null;$('app').hidden=true;connectionError=true;message(e.message,true);}}
async function remote(){try{const data=await api('/api/remote');const panel=$('remote');panel.replaceChildren();for(const n of data.nodes){const p=node('p');p.append(node('strong',n.address+' · '+n.status.toUpperCase()));p.append(node('span',' — '+(n.profileVersion==='lan-observe-v1'?'연결·자원 관측 전용':'프로필: '+n.profileVersion)));panel.append(p,node('p','마지막 heartbeat: '+(n.lastHeartbeatAt?new Date(n.lastHeartbeatAt).toLocaleString('ko-KR'):'없음'),'muted'));}if(!data.nodes.length)panel.append(node('p','등록된 원격 Node가 없습니다.'));panel.append(node('p','이 화면의 개발 작업은 현재 서버 PC에서 실행됩니다. 원격 PC 실행은 설치·검증 후 연결합니다.','muted'));}catch{$('remote').textContent='현재 원격 Node 정보를 읽을 수 없습니다.';}}
$('workspace').addEventListener('change',()=>{workspaceId=$('workspace').value;});
$('theme').addEventListener('click',()=>{document.documentElement.classList.toggle('light');$('theme').textContent=document.documentElement.classList.contains('light')?'어둡게':'밝게';});
$('refresh').addEventListener('click',()=>action(refresh));
$('newWorkspace').addEventListener('click',()=>action(async()=>{message('도구별 Workspace를 준비하고 있습니다…');const w=await api('/api/workspaces',{project:projectId,role:$('role').value});workspaceId=w.id;message('별도 Workspace가 준비되었습니다. 이제 도구를 여세요.');},$('newWorkspace')));
$('create').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.target);action(async()=>{const p=await api('/api/projects',{name:f.get('name'),kind:f.get('kind')});projectId=p.id;workspaceId=null;event.target.reset();message('새 프로젝트를 만들었습니다.');},event.submitter);});
$('budget').addEventListener('focusin',()=>{loading=true;});$('budget').addEventListener('focusout',()=>{loading=false;});
$('budget').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.target);action(async()=>{await api('/api/budget',Object.fromEntries([...f].map(([k,v])=>[k,Number(v)])));message('작업 자원 한도를 저장했습니다.');},event.submitter);});
(async()=>{const hash=new URLSearchParams(location.hash.slice(1));const token=hash.get('login');if(token){history.replaceState(null,'','/');try{await api('/api/login',{token});message('이 PC의 개발 환경에 로그인했습니다.');}catch(e){message(e.message,true);}}await refresh();if(state)await remote();setInterval(()=>{if(document.visibilityState==='visible')refresh();},4000);setInterval(()=>{if(state&&document.visibilityState==='visible')remote();},10000);})();
