-- SaintVision PostgreSQL Initial Database Bootstrap
-- Roles and grants are owned by migrations. Do not pre-create inv_app as LOGIN:
-- it is a NOLOGIN permission group, inherited by deployment-specific logins.
-- Existing clusters require a separately reviewed credential remediation;
-- changing this bootstrap does not revoke previously installed credentials.
