FROM golang@sha256:60deed95d3888cc5e4d9ff8a10c54e5edc008c6ae3fba6187be6fb592e19e8c0 AS build

WORKDIR /src
COPY services/node-agent ./services/node-agent
COPY packages/contracts-go ./packages/contracts-go
WORKDIR /src/services/node-agent
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -o /out/inv-node ./cmd/inv-node

FROM scratch
COPY --from=build /out/inv-node /inv-node
ENTRYPOINT ["/inv-node"]
